from datetime import timedelta

SQLALCHEMY_DATABASE_URI="sqlite:///../database_temp.sqlite"
SECRET_KEY="SECRET"
SQLALCHEMY_TRACK_MODIFICATIONS=False
SESSION_PERMANENT_LIFETIME=timedelta(days=30)
TEMPLATES_FOLDER="templates"
STATIC_FOLDER="static"
TELEGRAM_CHAT_ID=5091021565
TELEGRAM_BOT_TOKEN="6462602921:AAHmUMJE1X37nC66HEi0UNhg88M8muPGEfo"