"""empty message

Revision ID: 478992e9c424
Revises: b49056256acb
Create Date: 2024-05-12 18:20:29.927847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478992e9c424'
down_revision = 'b49056256acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_bet', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_bet', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
