"""empty message

Revision ID: 54633180563c
Revises: ef9dfbe49406
Create Date: 2024-05-05 23:56:29.769600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54633180563c'
down_revision = 'ef9dfbe49406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refs', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('refs')

    op.create_table('users',
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###
