"""empty message

Revision ID: 86834d884ce4
Revises: 45f78cd2e6cf
Create Date: 2024-09-01 01:46:55.778501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86834d884ce4'
down_revision = '45f78cd2e6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_analysis', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
