"""empty message

Revision ID: 964d075f107f
Revises: 54633180563c
Create Date: 2024-05-05 23:59:55.376226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964d075f107f'
down_revision = '54633180563c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refs', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('refs')

    op.create_table('users',
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###
