"""empty message

Revision ID: c3eb4d288907
Revises: 964d075f107f
Create Date: 2024-05-07 04:53:53.951380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3eb4d288907'
down_revision = '964d075f107f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('match_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('match_analysis_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_bet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_analysis_content', sa.TEXT(), nullable=True))
        batch_op.alter_column('match_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
