"""empty message

Revision ID: ca0c8bd6c57f
Revises: 2e1b3e3a9390
Create Date: 2024-05-28 00:53:53.187620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0c8bd6c57f'
down_revision = '2e1b3e3a9390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_expire', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sub_expire')

    # ### end Alembic commands ###
